# Site settings
title: Plays With Code
description: > # this means to ignore newlines until "baseurl:"
  I'm Ryan Scott. I play with code and build things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://playswithcode.com" # the base hostname & protocol for your site
twitter_username: rscott
github_username:  rscott
paginate:		  5

# Build settings
markdown: kramdown
